
SERVER_CHARACTER_STATE_ID = 0
SERVER_ABILITY_STARTED_ID = 1
SERVER_HIT_DETECTED_ID = 2
SERVER_CHARACTER_DEAD_ID = 3
SERVER_PROJECTILE_DEAD_ID = 4
SERVER_GAME_OVER_ID = 5

CLIENT_CHARACTER_INPUT = 6

def aaa():
    pass

